### ISSUE TITLE
Design and implement main page

### ISSUE THREAD

**Issue by cbeams** [bisq-network/wiki#10]
Should provide navigation to most important sections / categories of the wiki, especially knowledge base / howto articles, contributor / dao documentation, etc.

Look to https://en.bitcoin.it/wiki/Main_Page for inspiration.

**Comment by m52go** [comment]
This was completed in June.
https://github.com/bisq-network/projects/issues/8

See front page:
https://bisq.wiki/

@wiz would you mind closing this issue?
