### ISSUE TITLE
Skin the wiki with Bisq look and feel

### ISSUE THREAD

**Issue by cbeams** [bisq-network/wiki#12]
See https://www.mediawiki.org/wiki/Manual:Skins

- [x] @pedromvpg to design initial CSS based on default Vector Mediawiki skin
- [x] @wiz to implement
- [x] @pedromvpg to tighten up whitespace as requested by @cbeams

**Comment by cbeams** [comment]
@pedromvpg, this looks like it's already largely complete (thank you!). Could you respond here regarding my recent request from #wiki chat about tightening up the whitespace?

> @pedromvpg, the changes look amazing, and @wiz thanks for getting them in. I just have a couple items of quick feedback right now:
> 
> 1. Could we tighten up the whitespace? Compare https://bisq.wiki/Compensation with, e.g. https://en.wikipedia.org/wiki/Money and notice how much more efficient latter is with available real estate.

**Comment by pedromvpg** [comment]
White space reduced

<img width="1774" alt="Screen Shot 2020-03-31 at 1 28 51 AM" src="https://user-images.githubusercontent.com/807505/77990326-067fa400-72ef-11ea-9b83-5f364281f6a5.png">

**Comment by cbeams** [comment]
Closing as complete. The changes look good, thanks @pedromvpg.
