### ISSUE TITLE
Add dark mode option

### ISSUE THREAD

**Issue by cbeams** [bisq-network/wiki#13]
From #wiki chat between @cbeams and @wiz:

@cbeams wrote:
> 2. Dark mode (god bless you for adding it) doesn't persist across pages. If I click it once it applies for that page view, but when I navigate to any other page, I'm back to light mode. I assume this is a cookie thing.

> @wiz wrote
> 11:45 AM - Sun
> yeah I just added that real quick since pedro was working on it live
> of course a proper dark mode would be a user preference and persist somehow
> since you use stylish you already know about the really nice vector dark themes out there
> I can just import one of those into a new theme called DarkVector
> then the ordinary way to set user preference theme will work
> obviously inverting the color scheme doesn't result in a very nice looking dark mode
> it needs to be polished with 50 shades of gray

So, @wiz, @pedromvpg, this issue is just about doing whatever is necessary to make persisting the dark mode option a reality.

**Comment by wiz** [comment]
Fixed in 7450933
<img width="302" alt="Screen Shot 2020-02-27 at 0 30 43" src="https://user-images.githubusercontent.com/232186/75359922-6a7e0980-58f8-11ea-8000-637695645900.png">

**Comment by cbeams** [comment]
Thanks, @wiz. Closing as merged in the process of merging #15.

@pedromvpg, I'm not too thrilled with the default DarkVector L&F here. If you have any interest it tweaking it to feel more Bisq-ish, please do.

To enable the DarkVector skin, go to https://bisq.wiki/Special:Preferences#mw-prefsection-rendering, select DarkVector and hit Save.
