### ISSUE TITLE
Rework / streamline "Getting Started with Bisq" docs.bisq.network page

### ISSUE THREAD

**Issue by kemccall** [bisq-network/wiki#18]
Although this is on **docs.bisq.network** an equivalent guide is needed in the wiki. This guide is a critical onboarding document. It is an excellent starting point, but IMO in need of refinement.

It is a guide (a series of procedures) and not simply a use-case.

**Comment by Bayernatoor** [comment]
Hey @kemccall  - this guide was created on the wiki, https://bisq.wiki/Get_started - I worked on several of those pages but this was prior to having established a specific style guide, perhaps some of those pages require revisions.

**Comment by m52go** [comment]
FYI I'm creating a new page on the website that will serve as a thorough, interactive, versatile getting-started guide.

You can see details [here](https://github.com/bisq-network/bisq-website/issues/356).

I doubt there will be any overlap, but figured it worth mentioning here.

**Comment by kemccall** [comment]
Seems like I should probably just close this one. The new version sounds like a an even better idea.
