### ISSUE TITLE
Create payment method wiki

### ISSUE THREAD

**Issue by Bayernatoor** [bisq-network/wiki#20]
I've created the  'Payment methods' wiki page - https://bisq.wiki/Payment_methods. This seems to fall in the category of 'references' and so I did not remove too much of the wording from the original https://docs.bisq.network/payment-methods.html.

I cleaned it up and will create a separate page for account signing.

Any feedback is appreciated.

**Comment by kemccall** [comment]
Well done. I made a tiny style change. Reason - Unless there's a need to state a sequence for the "two measures",  an unordered list vs numbers is used.
