### ISSUE TITLE
Edit the "Find your mediator" article

### ISSUE THREAD

**Issue by kemccall** [bisq-network/wiki#33]
@wiz @Bisq-knight @pedromvpg @Plebeian9000   

Some suggested changes:

Using gerunds ( . . . ing) for process names is fairly standard in technical writing and we've adopted it in our style guide. So, this article name would change to _Finding your mediator_ and the sub heading _How to find the mediator_ would change to _Finding the mediator_.

Gerunds are generally shorter and more direct, particularly when doing a search. (Although _Find your mediator_ is an exception). All of the _How to's_ get shortened and you don't end up with a list of _How to this xxx_ and _How to that xxx_.

Also, I would change _Getting in touch_ to _Contacting_. _Getting in touch_  is a bit of a colloquialism. 

Anyway, let me know if there are objections to these potential changes.

**Comment by m52go** [comment]
> Using gerunds ( . . . ing) for process names is fairly standard in technical writing and we've adopted it in our style guide.

Sure, makes sense.

> Also, I would change _Getting in touch_ to _Contacting_. _Getting in touch_ is a bit of a colloquialism.

It's a minor colloquialism, but it's phrasing I would still consider to be professional and something anyone reading the wiki will understand. Bisq is already rather dense and hard to grasp...I think a touch of informality here and there can help to humanize it. 

This wiki is often technical in nature but I wouldn't strictly label it _technical writing_, in that it's not intended exclusively for technical audiences. We already have a wide variety of non-technical users, and hope to attract many more, so being somewhat relatable is also important.

This is just my opinion. You may want to see what others think.

For what it's worth, I go by Plebeian9000 on the wiki, so I made the bulk of the stylistic edits on this page. @MwithM originally wrote it.

**Comment by kemccall** [comment]
> > Using gerunds ( . . . ing) for process names is fairly standard in technical writing and we've adopted it in our style guide.
> 
> Sure, makes sense.
> 
> > Also, I would change _Getting in touch_ to _Contacting_. _Getting in touch_ is a bit of a colloquialism.
> 
> It's a minor colloquialism, but it's phrasing I would still consider to be professional and something anyone reading the wiki will understand. Bisq is already rather dense and hard to grasp...I think a touch of informality here and there can help to humanize it.
> 
> This wiki is often technical in nature but I wouldn't strictly label it _technical writing_, in that it's not intended exclusively for technical audiences. We already have a wide variety of non-technical users, and hope to attract many more, so being somewhat relatable is also important.
> > Agree.  My thinking on "getting in touch" was thinking as much about users who's primary language is not English. 
> This is just my opinion. You may want to see what others think.
> 
> For what it's worth, I go by Plebeian9000 on the wiki, so I made the bulk of the stylistic edits on this page. @MwithM originally wrote it.

**Comment by m52go** [comment]
Generally speaking, I recommend leaving an issue open until the underlying item is completed / dealt with. It seems like the edit in this issue (gerund) hasn't been made yet, so the issue should probably be left open until it is made.

Also not sure if it was a typo but I can't tell if you added any of your own commentary in the comment above.

**Comment by kemccall** [comment]
I did add commentary and thought I marked it correctly. Sorry. My commentary was:

_Agree. My thinking on "getting in touch" was thinking as much about users who's primary language is not English._

**Comment by kemccall** [comment]
Yes, I see the gerund issue hasn't been made - which as I recall is much more than just the title. So, yes, it's reopened.

**Comment by MwithM** [comment]
> For what it's worth, I go by Plebeian9000 on the wiki, so I made the bulk of the stylistic edits on this page. @MwithM originally wrote it

I just try to make it readable. I have a lot of difficulties to write a good ennough english, so I'll try to do my best and keep the guidestyle you find best.

**Comment by m52go** [comment]
All elements of this issue have been addressed and this issue can be closed.

https://bisq.wiki/Finding_your_mediator
