### ISSUE TITLE
Styling UI elements

### ISSUE THREAD

**Issue by m52go** [bisq-network/wiki#34]
@kemccall this was discussed on Keybase a while ago, with most people favoring `literals` for UI elements. The style guide currently specifies **bold** for UI elements.

Can this element of the style guide be changed? Do you have any further concerns?

**Comment by kemccall** [comment]
@m52go I believe the final outcome was (if I can quote exactly) Chris stating that, "anything a user clicks on or types" should be a literal. Personally, I think that is a bit too all encompassing and had previously started doing as you suggested. It's done extensively both ways.

We can change whatever we want. "Styles is styles" I'm flexible. What I'm striving for is consistency, and simplicity, and if there's a way to do that with less rework, even better. 

The original concept was to use the Wikipedia Manual of Styles, but there will always be deviations, and as I stated in the Style Guide there's a lot Wikipedia doesn't really cover.

The real issue for me is, how do we come to resolutions on these issues? And do so with the least of effort. I'm new to this decentralized, open source game, so . . .

**Comment by m52go** [comment]
> The real issue for me is, how do we come to resolutions on these issues?

My purpose in creating issues like this one was to create a forum for discussion so we can determine resolutions. 

Did you intend to close this issue? I think it would be better to leave it open until we've determined a resolution and/or it's put into practice.
