### ISSUE TITLE
Determine policy for non-English wiki pages

### ISSUE THREAD

**Issue by m52go** [bisq-network/wiki#35]
@kemccall currently, the wiki style guide says:

> Until there is a need for separate language wikis, create articles in the non English language with the English translation in comments. See Running Bisq in China as an example. 

There is a chance we'll have more Spanish translations of existing materials in the next couple of months as part of a growth effort in Latin American markets.

**How should these items be handled, if they become a reality?**

Like I originally said way back when the article on running Bisq in China was written, that article is a one-off. It's not likely to be followed with any more Chinese items in the near future, and more importantly, it wasn't clear **who** would be reading the article to begin with. The target readership for that article seemed to prefer a mix of Chinese and English, and a few days later, someone from India found the article valuable. So English needed to be visible along with Chinese.

But, unlike that Chinese page, most non-English articles will probably be translations of existing articles, not one-offs, where the English will already be readily available elsewhere...so the policy on non-English pages should be created accordingly.

**Comment by kemccall** [comment]
@m52go I'm for simply deleting my original idea in the style guide.

**Comment by m52go** [comment]
Okay, but how should we handle this when it comes up in the future? Spanish, for example, where most items will probably be translations. I think a separate wiki instance would be overkill at first.

**Comment by kemccall** [comment]
@m52go As you said on this one, it's a one-off situation. So, this issue IMO should be Closed.

For translations in general, I would hope that they are simply a matter of translating an existing topic, as you say. How we deal with that? I'd look to how others have done it. Which requires research.
