### ISSUE TITLE
Designate high-priority articles for translation

### ISSUE THREAD

**Issue by m52go** [bisq-network/wiki#37]
There are now a couple of contributors I'm working with in Spanish-speaking and Chinese-speaking markets who want to see documentation translated to help their users better understand Bisq, how it works, and how to use it.

This is an understandable desire. 

But it raises a concern: how should translation of docs/wiki articles be handled? Surely not all articles in the English wiki should be up for translation. There are many languages and many markets. It doesn't seem reasonable that the DAO should be on the hook for paying for every single article to be translated for every new market. Only a few are critical for getting going. 

Furthermore, the maintenance burden of keeping many articles updated for many languages would be enormous.

Therefore I think it's time we designate a **minimal list of high-priority articles for translation**—the bare minimum a new user in a new market would need to get up and running. Likely candidates: project overview/introduction, trading rules, payment methods, fees, etc. Translations of any further articles would be discouraged, both because they wouldn't be useful for starting trading and because of the maintenance burden.

I haven't gone through and determined exactly what this list should be yet, but I will soon. I just want to make this issue first to gather any other thoughts in the mean time.

**Comment by cbeams** [comment]
> Surely not all articles in the English wiki should be up for translation.

👍, agreed that any such paid wiki translations should be case-by-case according to merit / actual demand.

**Comment by m52go** [comment]
This initiative lost priority since the market makers from the time stepped away, but a conclusion should be reached anyway so we're better-prepared next time.

In the interim, the featured article list on bisq.wiki is now quite comprehensive. I think it covers everything except the DAO.

![Screenshot from 2020-07-30 15-41-10](https://user-images.githubusercontent.com/735155/88967176-6aa17d00-d27b-11ea-9d15-ba550479ccd0.png)

I suggest the following articles for a high-priority translation list:
- Introduction
- Getting started (on website)
- Downloading and installing (not the existing article, but an abbreviated article that isn't so long, as suggested by @mwithm)
- Backing up critical data (both articles)
- Payment methods
- Trading fees
- Dispute resolution
- Contributor checklist (once it's ported over to the wiki from docs)

Keep in mind that the FAQs page on the website will be updated and translated too for concise answers to common questions.

It would be nice to include an introductory DAO article here at some point, but I don't think it's critical, especially if the goal is simply to get people in new markets trading.

**Comment by MwithM** [comment]
We should count how many words are on this articles and maybe abbreviate other articles other than download and install, so translating this pages to a wide range of languages won't be too costly and we will be able to translate this articles to other languages different than core translating languages.

[FAQ page](https://bisq.wiki/Help:FAQ) is already up to date on the wiki, but I think it might need big changes to make it more appealing.

**Comment by m52go** [comment]
@bayernatoor and I are working on completing the docs transition, so the contributor checklist should be available on the wiki soon. Then the downloading and installing article needs to be abridged.

But the point of this issue was to determine what that list should be, and as [this list](https://github.com/bisq-network/wiki/issues/37#issuecomment-666644730) seems to be good for now, I'll close this issue.
