### ISSUE TITLE
Transcribe DAO docs to wiki

### ISSUE THREAD

**Issue by Bayernatoor** [bisq-network/wiki#39]
The huge task of moving the Bisq documentation from the [Bisq website]( https://docs.bisq.network/) to the [Bisq wiki](https://bisq.wiki/Main_Page) is well underway. 

One of the last remaining pieces is the DAO. The task itself is not very complicated but organizing and structuring it in a way that makes sense is very important due to the amount of information and to ensure that users/contributors can easily find the information they need. 

Therefore, @m52go  and I decided to open an issue so that anyone interested in pitching in/helpingcould easily participate. 

We believe that we have a decent structure in place but we're obviously open to feedback: 
(rough draft)

![2](https://user-images.githubusercontent.com/55212954/93003975-c44ac780-f508-11ea-8519-9db8300a07f0.png)

Currently working on the top level heading: https://bisq.wiki/Introduction_to_the_DAO

I've mainly just transcribed what was on https://docs.bisq.network/user-dao-intro.html. The idea is to get a rough structure in place, getting every article linked to the "One-stop-shop-DAO Page" and then from there transcribing most of the articles. 

Suggestions on articles names would be great. I'll likely copy what we have in the Bisq Docs for now.

**Comment by Bayernatoor** [comment]
Current view of the [one stop shop page](https://bisq.wiki/Decentralized_autonomous_organization). Included the introduction paragraph on that page to give it a bit of substance and removed it from the [Intro](https://bisq.wiki/Introduction_to_the_DAO) article. 

Moved seed and price node guides to "User Guides & Use Cases", open to discussion, not sure if that's the best spot. 

Lots left to transcribe.

**Comment by m52go** [comment]
I'm liking the direction this is going in! Thanks @Bayernatoor for taking the lead on this.

I guess it may be unclear from the old docs website but seednode and pricenode guides are generally unrelated to the DAO topic and can be removed from the one-stop page.

**Comment by Bayernatoor** [comment]
Thanks for the feedback! I was unsure where the seednode pricenode guides should reside. I'll transcribe them over eventually but they wont be part of the DAO guide!

**Comment by Bayernatoor** [comment]
Although some touch ups may be necessary:
https://bisq.wiki/DAO_user_guide_for_traders
https://bisq.wiki/DAO_user_guide_for_contributors
Are now complete.

Next up will be:
https://bisq.wiki/Contributor_checklist
https://bisq.wiki/DAO_user_reference --> no longer required 
https://bisq.wiki/DAO_technical_overview

**Comment by Bayernatoor** [comment]
Both of these are now complete:
https://bisq.wiki/Contributor_checklist
https://bisq.wiki/DAO_technical_overview

This marks the completion of the majority of the DAO docs. 

The https://bisq.wiki/DAO_user_reference will be removed since most of the information contained in that Doc can be found elsewhere. A dedicated BSQ Token page needs to be created as well. 

There are a few more (smallish) pages remaining and many links need to be corrected (I will be going through and fixing these in the coming days)

https://bisq.wiki/Submit_compensation_request
https://bisq.wiki/File_compensation_request_in_the_DAO
https://bisq.wiki/BSQ_token

I will continue to update as progress is made.

**Comment by m52go** [comment]
This was recently completed. 

All DAO articles are linked on this page: 
https://bisq.wiki/Decentralized_autonomous_organization
