### ISSUE TITLE
Running_Bisq_on_Tails at least needs a disclaimer

### ISSUE THREAD

**Issue by nayfield** [bisq-network/wiki#40]
At *least* add commentary along the lines of

"Following these directions will allow you to run Bisq in Tails *until you reboot*.  It is not persistent.  You will need to repeat these steps on each boot of tails and start over."

---

Better yet - document a method of installing Bisq that *is* persistent on Tails.  

This is possible using the persistence feature of installing packages.  It may require Bisq to be published to the set of apt repositories Tails is configured with ... or petition tails to add your apt repository to their sources ... but with some configuration (saving data to persistence) it would definitely be possible to do.  May require a tails-specific package/repo to provide the hooks to do the manual post dkpg steps in the current wiki within the package which would get installed from persistence on each boot.

**Comment by m52go** [comment]
Thanks, added.

It seems the guide was written with the expectation that the user would set up persistent storage, since it's listed in [Preparations](https://bisq.wiki/Running_Bisq_on_Tails#Preparations).

Anyway I've added a warning to the [Install](https://bisq.wiki/Running_Bisq_on_Tails#Install) section.

@freimair if there's anything in particular you think could/should be added to help, please do.

**Comment by nayfield** [comment]
Yes at a minimum you need to install via apt not dpkg directly - the way
additional software persistence works in tails is that it installs apt
packages (from the persistent partition) to the ramdisk overlay each boot
when persistence is unlocked.

**Comment by freimair** [comment]
@nayfield your are saying that

`Do a simple sudo apt install ./[yourbinaryhere]`

would be the proper way?

**Comment by nayfield** [comment]
You would need to include the specific other steps in the package (like
onion grater config too ...)

But basically they have a hook to allow persistent installs.  Not sure of
the cmdline details but there is a guide here.

https://tails.boum.org/doc/first_steps/additional_software/index.en.html

(Look at persistence docs).

My suggestion would to

1. Create a variant or sidecar package that does the non dpkg steps in the
current guide

2. Just point to that tails upstream doc and have the user follow that

**Comment by nayfield** [comment]
I'd suggest reopening this - the warning doesn't help a tails user unless they want to test things out one time.  It all goes away at reboot.

But I do see value of Bisq on tails if done correctly.

I have a feature proposal in tails upstream that they need to commit before this will work ... 

But I can see a path to a script that would make bisq work on tails in an 'expected' fashion (e.g. reboot tails and you still have your stuff)

I would need the bisq project to do two things:
1. Provide bisq via an apt repo instead of a dkpg download
2. update the bisq package to install a shell script that never gets run on a normal install

The second item lets bisq upstream be in control of future from an upgrade perspective - the tail install instructions (both steps) would let Bisq change the file that is only used for those who do step 2 and provide an upgrade hook every time a tail install boots.

This is the most sustainable concept I can come up with - if future tails breaks bisq you have a hook to fix the breakage on the next boot once you update your package.

**Comment by nayfield** [comment]
https://github.com/bisq-network/bisq/issues/4563

https://github.com/bisq-network/bisq/issues/4564

If you can re-open this issue I can provide a PR against it once the dependencies are resolved.  (two in bisq and one in tails - and I'm proposing to provide the PR for 2 of the 3.  I could easily implement the third but I'm not a bisq website admin)

**Comment by josibake** [comment]
I also think this issue should be re-opened. I just completed the wiki instructions after setting up persistent storage and it does not result in a persistent install. I tested this by rebooting tails and I did not have Bisq installed.

I think in addition to what @nayfield mentioned, wouldn't the default directory for Bisq need to be changed to the `Persistent` directory on tails?

**Comment by amosgroth** [comment]
Hi. I have run into the same problem but I managed to install Bisq on Tails permanently and would like to share a step-by-step guide on this Wiki page for other users to do so.

**Comment by m52go** [comment]
@amosgroth that's awesome -- people have been asking about that lately! Would you mind posting your guide here?

Then we can get someone with access to the wiki to edit & post it there. We don't provide public edit access to the wiki any more after incidents with spam and abuse.

**Comment by amosgroth** [comment]
Here we go:

https://github.com/amosgroth/docs/blob/master/Bisq/Running%20Bisq%20on%20Tails.wt

Since I am not running MediaWiki and I couldn't find a fast way to view the outcome (html), please feel free to try and review.

**Comment by w0000000t** [comment]
utACK: https://bisq.wiki/Running_Bisq_on_Tails#Persistent_Data_Directory

**Comment by amosgroth** [comment]
I am not finally happy with it. Using the dotfiles works but it seems like Bisq is storing the chain data somewhere else (and Tails deletes them) so Bisq has to synch over and over again after restarts...

**Comment by w0000000t** [comment]
Feel free to let me know about possible updates... in any case, all data should still be inside the data directory, there's nowhere else I know of that Bisq saves its data
