### ISSUE TITLE
Add to the Amazon Gift card article

### ISSUE THREAD

**Issue by Bisq-knight** [bisq-network/wiki#42]
In Europe we have multiple amazon sites (.fr, .es. .de, .it and even .se) and even though all are in EUR (except for SE) gift cards cannot be sent across websites. Which causes the need to buyer and seller to agree on where to buy the gift card so the trade can work.

What to Add to the [Article](https://bisq.wiki/Amazon_eGift_card):
* If in EUR, please confirm with your peer which site to be used for the transaction

I'm discussing with @pazza83 how we can solve this in the payment method itself. For now it would avoid errors to communicate this before we can implement a long-term solution

**Comment by m52go** [comment]
Thanks @Bisq-knight, added to the article [here](https://bisq.wiki/Amazon_eGift_card#Step_1._Log_in_to_Amazon).
