### ISSUE TITLE
Qubes instructions in wiki incomplete

### ISSUE THREAD

**Issue by unman** [bisq-network/wiki#43]
It isn't possible to install bisq using the instructions in the wiki.for Qubes.
This is because `bind-dirs` will not create a directory that is not already present, so the installation of the Bisq deb will fail.
It's necessary to manually create `/usr/share/desktop-directories` *before* restarting the qube to apply binding dir settings. (You can do this before or after setting up the bind-dirs.)

**Comment by m52go** [comment]
Implemented with https://bisq.wiki/index.php?title=Running_Bisq_on_Qubes&diff=2238&oldid=1748.
