### ISSUE TITLE
Wrong denomination in "BSQ trading fees" spreadsheet

### ISSUE THREAD

**Issue by RequestPrivacy** [bisq-network/wiki#47]
I hope this is the right place for my issue as I discovered it while browsing the wiki and learning about the DAO.

Under the [Updating BSQ trading fees](https://bisq.wiki/Updating_BSQ_trading_fees) side there is a link to the [spreadsheet ](https://docs.google.com/spreadsheets/d/1-hISy7F0NSqPnRxDOoi1k7df1qLJHfQTxhrVLt6NbX4/edit#gid=0) where the BSQ fees for the next cycle are determined transparently. The wiki states:

> Three days before the end of proposal phase, the Compensation Maintainer shall: 
> - Calculate BSQ trading fee discount on this spreadsheet using the 30-day weighted average **USD/BSQ price** and live USD/BTC price at the time. 

Shouldn't therefore cell A4 state 30D WMA USD/**BSQ** instead of USD/BTC?

![BSQ_trading_fees_spreadsheet](https://user-images.githubusercontent.com/72392544/146215706-ad74bde4-7bf0-45e2-ae58-cf789ea07a0f.png)

**Comment by m52go** [comment]
Seems like you're right...paging @mwithm.

**Comment by MwithM** [comment]
Thanks, changed.
