### ISSUE TITLE
Change Cash by Mail info in Payment_Methods

### ISSUE THREAD

**Issue by stopfeds** [bisq-network/wiki#49]
The infos for Cash by Mail in the [Payment Methods Wiki](https://bisq.wiki/Payment_methods) are wrong.

![image](https://user-images.githubusercontent.com/71401614/154564879-1d2eeca2-d198-4dc1-9236-1be7026bd4a1.png)

Region needs to be changed to "Global" and notes can be changed to something like:

`Please check [the article](https://bisq.wiki/Cash_by_Mail) and follow the recommendations to avoid disputes`

**Comment by ghost** [comment]
Done.
