### ISSUE TITLE
Transfer ownership of bisq.wiki domain name

### ISSUE THREAD

**Issue by cbeams** [bisq-network/wiki#7]
@cbeams originally purchased the bisq.wiki domain in bisq-network/wiki#1, but it should now be transferred to @wiz in his role as Wiki Operator (bisq-network/roles#92).

- [x] @wiz to instruct @cbeams about how to proceed with the transfer
- [x] @cbeams to follow instructions
- [ ] @wiz to complete the transfer process

**Comment by cbeams** [comment]
@wiz pointed out I need to follow the instructions at https://docs.gandi.net/en/domain_names/change_owner/standard_process.html#step-one-launch-the-order. I am doing that now.

**Comment by cbeams** [comment]
I've initiated the domain transfer per the instructions above. I believe the ball is now in @wiz's court to complete the process. Gandi order ID is 52783355.

**Comment by wiz** [comment]
I have taken ownership of the bisq.wiki domain name

**Comment by cbeams** [comment]
Confirmed from my side as well. Closing as complete.
