### ISSUE TITLE
Establish regular backup process

### ISSUE THREAD

**Issue by cbeams** [bisq-network/wiki#8]
Follow whatever typical mediawiki conventions are for doing backups.

- [x] Make sure doing these backups, how often they're done, where they're stored, etc are mentioned in the duties section of the https://bisq.wiki/Wiki_Operator role documentation. A Process section may be created to expand on the details.

**Comment by wiz** [comment]
Daily backups of the MySQL database dump and full webroot archive are now being saved and uploaded to a secure off-site location
