### ISSUE TITLE
Create style guidelines article

### ISSUE THREAD

**Issue by cbeams** [bisq-network/wiki#9]
From a conversation between @m52go and @cbeams at https://github.com/bisq-network/projects/issues/6#issuecomment-586901368:

> > Is there any place we can put wiki contribution guidelines/suggestions? Maybe just create a new page for it?
> 
> Just a new page is fine for a start. See 
> 
>  - https://en.wikipedia.org/wiki/Category:Wikipedia_style_guidelines
>  - https://en.wikipedia.org/wiki/Wikipedia:List_of_guidelines
> 
> for reference. Perhaps a page simply titled https://bisq.wiki/Guidelines would be fine for now, simply listing out the various guidelines and rules we'd like to establish.
> 
> 
> 
> > I'm particularly interested in specifying that screenshots should omit the OS window border, since everyone runs something different
> 
> True, but in my experience, the convenience of CMD-SHIFT-4-SPACE whole-window screenshots on macOS are important. And they look very attractive because they capture the drop shadow. I'm not opposed to a style guideline that says that all such screenshots should crop out window trim and shadows, but I'm not sure the end result will actually be better for it. If someone does a guide from ubuntu and captures the look and feel there, and most others do it from macOS, it's not the biggest deal to me personally. Also, some articles may include screenshots of non-Bisq windows, e.g. finder/explorer windows, and there is no way to hide the os-specificity there. Again, I don't have a very strong opinion on this.
> 
> > and to use the same template for all arrows (I have one I've used for all arrows on docs.bisq.network).
> 
> Seems like a good idea. Just wonder if there's actually a common toolset that people will be able to use. I've always liked using Skitch for quickly marking up screenshots. But whatever you see fit.

**Comment by cbeams** [comment]
As mentioned in the screencast at bisq-network/wiki#16, I've just created https://bisq.wiki/Wiki_style_guidelines for this purpose. Please continue building out any guidelines there.

**Comment by m52go** [comment]
This was also completed in June.
https://bisq.wiki/Wiki_style_guidelines

Notable additions in June:
- [add markup and templates for admonitions](https://bisq.wiki/Wiki_style_guidelines#Use_admonition_blocks_for_stand-out_warnings_and_notes)
- guidelines on images (Bisq screenshots, sizing, marking up with arrows, etc)

@wiz would you mind closing this issue?
